name: snake_ai
description: A new Flutter project.

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">= 3.0.0"

dependencies:
  flame: ^1.2.0
  flame_svg: ^1.4.0
  flutter:
    sdk: flutter
  provider: ^6.0.3
  yaru: ^0.3.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
